// Generated by scripts/generate-lom.mjs from https://docs.cycling74.com/apiref/lom/ — do not edit by hand.

/**
 * LOM members whose value is always a list (list children like `devices`, and
 * list-typed properties like StringVector), even when Live returns one element.
 */
const LIST_MEMBERS: ReadonlySet<string> = new Set([
  "arrangement_clips",
  "audio_inputs",
  "audio_outputs",
  "available_warp_modes",
  "chains",
  "clip_slots",
  "control_surfaces",
  "cue_points",
  "devices",
  "drum_pads",
  "grooves",
  "ir_category_list",
  "ir_file_list",
  "midi_inputs",
  "midi_outputs",
  "mod_matrix_filter_source_1_list",
  "mod_matrix_filter_source_2_list",
  "mod_matrix_lfo_source_list",
  "mod_matrix_pitch_source_1_list",
  "mod_matrix_pitch_source_2_list",
  "mod_matrix_shape_source_list",
  "mod_matrix_source_1_list",
  "mod_matrix_source_2_list",
  "mod_matrix_source_3_list",
  "mod_matrix_target_1_list",
  "mod_matrix_target_2_list",
  "mod_matrix_target_3_list",
  "oscillator_1_wavetables",
  "oscillator_2_wavetables",
  "oscillator_wavetable_categories",
  "parameters",
  "presets",
  "record_length_list",
  "return_chains",
  "return_tracks",
  "routing_mode_list",
  "scale_intervals",
  "scenes",
  "sends",
  "slices",
  "take_lanes",
  "tracks",
  "value_items",
  "visible_drum_pads",
  "visible_modulation_target_names",
  "visible_tracks",
  "voice_count_list",
  "voice_mode_list",
]);

interface ClassMembers {
  /** The class this one inherits members from. */
  parent?: string;
  /** Children and properties declared on this class (not inherited). */
  values: string[];
  /** Functions declared on this class (not inherited). */
  functions: string[];
}

/** Members declared by each LOM class, used to resolve dynamic accessors. */
const CLASS_MEMBERS: Record<string, ClassMembers> = {
  "Application": { values: ["view","control_surfaces","current_dialog_button_count","current_dialog_message","open_dialog_count","average_process_usage","peak_process_usage"], functions: ["get_bugfix_version","get_document","get_major_version","get_minor_version","get_version_string","press_current_dialog_button"] },
  "Application.View": { values: ["browse_mode","focused_document_view"], functions: ["available_main_views","focus_view","hide_view","is_view_visible","scroll_view","show_view","toggle_browse","zoom_view"] },
  "Chain": { values: ["devices","mixer_device","color","color_index","is_auto_colored","has_audio_input","has_audio_output","has_midi_input","has_midi_output","mute","muted_via_solo","name","solo"], functions: ["delete_device","insert_device"] },
  "ChainMixerDevice": { values: ["sends","chain_activator","panning","volume"], functions: [] },
  "Clip": { values: ["view","groove","available_warp_modes","color","color_index","end_marker","end_time","gain","gain_display_string","file_path","has_envelopes","has_groove","is_session_clip","is_arrangement_clip","is_take_lane_clip","is_audio_clip","is_midi_clip","is_overdubbing","is_playing","is_recording","is_triggered","launch_mode","launch_quantization","legato","length","loop_end","loop_jump","loop_start","looping","muted","name","notes","warp_markers","pitch_coarse","pitch_fine","playing_position","playing_status","position","ram_mode","sample_length","sample_rate","signature_denominator","signature_numerator","start_marker","start_time","velocity_amount","warp_mode","warping","will_record_on_start"], functions: ["add_new_notes","add_warp_marker","apply_note_modifications","clear_all_envelopes","clear_envelope","crop","deselect_all_notes","duplicate_loop","duplicate_notes_by_id","duplicate_region","fire","get_all_notes_extended","get_notes_by_id","get_notes_extended","get_selected_notes_extended","move_playing_pos","move_warp_marker","quantize","quantize_pitch","remove_notes_by_id","remove_notes_extended","remove_warp_marker","scrub","select_all_notes","select_notes_by_id","set_fire_button_state","stop","stop_scrub"] },
  "Clip.View": { values: ["grid_is_triplet","grid_quantization"], functions: ["hide_envelope","select_envelope_parameter","show_envelope","show_loop"] },
  "ClipSlot": { values: ["clip","color","color_index","controls_other_clips","has_clip","has_stop_button","is_group_slot","is_playing","is_recording","is_triggered","playing_status","will_record_on_start"], functions: ["create_audio_clip","create_clip","delete_clip","duplicate_clip_to","fire","set_fire_button_state","stop"] },
  "CompressorDevice": { parent: "Device", values: ["available_input_routing_channels","available_input_routing_types","input_routing_channel","input_routing_type"], functions: [] },
  "ControlSurface": { values: ["pad_layout"], functions: ["get_control","get_control_names","grab_control","grab_midi","register_midi_control","release_control","release_midi","send_midi","send_receive_sysex"] },
  "CuePoint": { values: ["name","time"], functions: ["jump"] },
  "Device": { values: ["parameters","view","can_have_chains","can_have_drum_pads","class_display_name","class_name","is_active","name","type","latency_in_samples","latency_in_ms","can_compare_ab","is_using_compare_preset_b"], functions: ["store_chosen_bank","save_preset_to_compare_ab_slot"] },
  "Device.View": { values: ["is_collapsed"], functions: [] },
  "DeviceIO": { values: ["available_routing_channels","available_routing_types","default_external_routing_channel_is_none","routing_channel","routing_type"], functions: [] },
  "DeviceParameter": { values: ["automation_state","default_value","is_enabled","is_quantized","max","min","name","original_name","state","value","display_value","value_items"], functions: ["re_enable_automation","str_for_value","__str__"] },
  "DriftDevice": { parent: "Device", values: ["mod_matrix_filter_source_1_index","mod_matrix_filter_source_1_list","mod_matrix_filter_source_2_index","mod_matrix_filter_source_2_list","mod_matrix_lfo_source_index","mod_matrix_lfo_source_list","mod_matrix_pitch_source_1_index","mod_matrix_pitch_source_1_list","mod_matrix_pitch_source_2_index","mod_matrix_pitch_source_2_list","mod_matrix_shape_source_index","mod_matrix_shape_source_list","mod_matrix_source_1_index","mod_matrix_source_1_list","mod_matrix_source_2_index","mod_matrix_source_2_list","mod_matrix_source_3_index","mod_matrix_source_3_list","mod_matrix_target_1_index","mod_matrix_target_1_list","mod_matrix_target_2_index","mod_matrix_target_2_list","mod_matrix_target_3_index","mod_matrix_target_3_list","pitch_bend_range","voice_count_index","voice_count_list","voice_mode_index","voice_mode_list"], functions: [] },
  "DrumCellDevice": { parent: "Device", values: ["gain"], functions: [] },
  "DrumChain": { parent: "Chain", values: ["in_note","out_note","choke_group"], functions: [] },
  "DrumPad": { values: ["chains","mute","name","note","solo"], functions: ["delete_all_chains"] },
  "Eq8Device": { parent: "Device", values: ["edit_mode","global_mode","oversample"], functions: [] },
  "Eq8Device.View": { parent: "Device.View", values: ["selected_band"], functions: [] },
  "Groove": { values: ["base","name","quantization_amount","random_amount","timing_amount","velocity_amount"], functions: [] },
  "GroovePool": { values: ["grooves"], functions: [] },
  "HybridReverbDevice": { parent: "Device", values: ["ir_attack_time","ir_category_index","ir_category_list","ir_decay_time","ir_file_index","ir_file_list","ir_size_factor","ir_time_shaping_on"], functions: [] },
  "LooperDevice": { parent: "Device", values: ["loop_length","overdub_after_record","record_length_index","record_length_list","tempo"], functions: ["clear","double_speed","half_speed","double_length","half_length","record","overdub","play","stop","undo","export_to_clip_slot"] },
  "MaxDevice": { parent: "Device", values: ["audio_inputs","audio_outputs","midi_inputs","midi_outputs"], functions: ["get_bank_count","get_bank_name","get_bank_parameters"] },
  "MeldDevice": { parent: "Device", values: ["selected_engine","unison_voices","mono_poly","poly_voices"], functions: [] },
  "MixerDevice": { values: ["sends","cue_volume","crossfader","left_split_stereo","panning","right_split_stereo","song_tempo","track_activator","volume","crossfade_assign","panning_mode"], functions: [] },
  "PluginDevice": { parent: "Device", values: ["presets","selected_preset_index"], functions: [] },
  "RackDevice": { parent: "Device", values: ["chain_selector","chains","drum_pads","return_chains","visible_drum_pads","can_show_chains","has_drum_pads","has_macro_mappings","is_showing_chains","variation_count","selected_variation_index","visible_macro_count"], functions: ["copy_pad","add_macro","insert_chain","remove_macro","randomize_macros","store_variation","recall_selected_variation","recall_last_used_variation","delete_selected_variation"] },
  "RackDevice.View": { parent: "Device.View", values: ["selected_drum_pad","selected_chain","drum_pads_scroll_position","is_showing_chain_devices"], functions: [] },
  "RoarDevice": { parent: "Device", values: ["routing_mode_index","routing_mode_list","env_listen"], functions: [] },
  "Sample": { values: ["beats_granulation_resolution","beats_transient_envelope","beats_transient_loop_mode","complex_pro_envelope","complex_pro_formants","end_marker","file_path","gain","length","sample_rate","slices","slicing_sensitivity","start_marker","texture_flux","texture_grain_size","tones_grain_size","warp_markers","warp_mode","warping","slicing_style","slicing_beat_division","slicing_region_count"], functions: ["gain_display_string","insert_slice","move_slice","remove_slice","clear_slices","reset_slices"] },
  "Scene": { values: ["clip_slots","color","color_index","is_empty","is_triggered","name","tempo","tempo_enabled","time_signature_numerator","time_signature_denominator","time_signature_enabled"], functions: ["fire","fire_as_selected","set_fire_button_state"] },
  "ShifterDevice": { parent: "Device", values: ["pitch_bend_range","pitch_mode_index"], functions: [] },
  "SimplerDevice": { parent: "Device", values: ["sample","can_warp_as","can_warp_double","can_warp_half","multi_sample_mode","pad_slicing","playback_mode","playing_position","playing_position_enabled","retrigger","slicing_playback_mode","voices"], functions: ["crop","guess_playback_length","reverse","warp_as","warp_double","warp_half"] },
  "SimplerDevice.View": { parent: "Device.View", values: ["selected_slice"], functions: [] },
  "Song": { values: ["cue_points","return_tracks","scenes","tracks","visible_tracks","master_track","view","groove_pool","tuning_system","appointed_device","arrangement_overdub","back_to_arranger","can_capture_midi","can_jump_to_next_cue","can_jump_to_prev_cue","can_redo","can_undo","clip_trigger_quantization","count_in_duration","current_song_time","exclusive_arm","exclusive_solo","file_path","groove_amount","is_ableton_link_enabled","is_ableton_link_start_stop_sync_enabled","is_counting_in","is_playing","last_event_time","loop","loop_length","loop_start","metronome","midi_recording_quantization","name","nudge_down","nudge_up","tempo_follower_enabled","overdub","punch_in","punch_out","re_enable_automation_enabled","record_mode","root_note","scale_intervals","scale_mode","scale_name","select_on_launch","session_automation_record","session_record","session_record_status","signature_denominator","signature_numerator","song_length","start_time","swing_amount","tempo"], functions: ["capture_and_insert_scene","capture_midi","continue_playing","create_audio_track","create_midi_track","create_return_track","create_scene","delete_scene","delete_track","delete_return_track","duplicate_scene","duplicate_track","find_device_position","force_link_beat_time","get_beats_loop_length","get_beats_loop_start","get_current_beats_song_time","get_current_smpte_song_time","is_cue_point_selected","jump_by","jump_to_next_cue","jump_to_prev_cue","move_device","play_selection","re_enable_automation","redo","scrub_by","set_or_delete_cue","start_playing","stop_all_clips","stop_playing","tap_tempo","trigger_session_record","undo"] },
  "Song.View": { values: ["detail_clip","highlighted_clip_slot","selected_chain","selected_parameter","selected_scene","selected_track","draw_mode","follow_song"], functions: ["select_device"] },
  "SpectralResonatorDevice": { parent: "Device", values: ["frequency_dial_mode","midi_gate","mod_mode","mono_poly","pitch_mode","pitch_bend_range","polyphony"], functions: [] },
  "TakeLane": { values: ["arrangement_clips","name"], functions: ["create_audio_clip","create_midi_clip"] },
  "Track": { values: ["take_lanes","clip_slots","arrangement_clips","devices","group_track","mixer_device","view","arm","available_input_routing_channels","available_input_routing_types","available_output_routing_channels","available_output_routing_types","back_to_arranger","can_be_armed","can_be_frozen","can_show_chains","color","color_index","fired_slot_index","fold_state","has_audio_input","has_audio_output","has_midi_input","has_midi_output","implicit_arm","input_meter_left","input_meter_level","input_meter_right","input_routing_channel","input_routing_type","is_foldable","is_frozen","is_grouped","is_part_of_selection","is_showing_chains","is_visible","mute","muted_via_solo","name","output_meter_left","output_meter_level","output_meter_right","performance_impact","output_routing_channel","output_routing_type","playing_slot_index","solo"], functions: ["create_audio_clip","create_midi_clip","create_take_lane","delete_clip","delete_device","duplicate_clip_slot","duplicate_clip_to_arrangement","insert_device","jump_in_running_session_clip","stop_all_clips"] },
  "Track.View": { values: ["selected_device","device_insert_mode","is_collapsed"], functions: ["select_instrument"] },
  "TuningSystem": { values: ["name","pseudo_octave_in_cents","lowest_note","highest_note","reference_pitch","note_tunings"], functions: [] },
  "WavetableDevice": { parent: "Device", values: ["filter_routing","mono_poly","oscillator_1_effect_mode","oscillator_2_effect_mode","oscillator_1_wavetable_category","oscillator_2_wavetable_category","oscillator_1_wavetable_index","oscillator_2_wavetable_index","oscillator_1_wavetables","oscillator_2_wavetables","oscillator_wavetable_categories","poly_voices","unison_mode","unison_voice_count","visible_modulation_target_names"], functions: ["add_parameter_to_modulation_matrix","get_modulation_target_parameter_name","get_modulation_value","is_parameter_modulatable","set_modulation_value"] },
};

export = { LIST_MEMBERS, CLASS_MEMBERS };
